name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up virtual environment
        run: |
          python -m venv venv  

      - name: Install dependencies
        run: |
          source venv/bin/activate 
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          export PYTHONPATH="${{ github.workspace }}"
          pytest

      - name: Docker build
        run: |
          docker build -t fastapi-devex .
